CREATE TABLE AUTHORS (
	AUTHOR_ID INT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL UNIQUE,
	EMAIL VARCHAR(255) NOT NULL UNIQUE
);

ALTER TABLE AUTHORS ALTER COLUMN name SET NOT NULL;
ALTER TABLE AUTHORS ADD CONSTRAINT name_unq UNIQUE(NAME);

CREATE TABLE BOOKS (
	BOOK_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL UNIQUE,
	DESCRIPTION VARCHAR(255) NOT NULL,
	DATE_CREATED TIMESTAMPTZ NOT NULL,
	LAST_DATE_UPDATED TIMESTAMPTZ,
	AUTHOR_ID INT NOT NULL,
	CONSTRAINT fk_author
      FOREIGN KEY(AUTHOR_ID) 
      REFERENCES AUTHORS(AUTHOR_ID)
);

CREATE TABLE BOOK_SALES (
	BOOK_SALE_ID SERIAL PRIMARY KEY,
	PRICE_SOLD INT NOT NULL,
	DATE_SOLD TIMESTAMPTZ NOT NULL,
	BOOK_ID INT NOT NULL,
	CONSTRAINT fk_book
      FOREIGN KEY(BOOK_ID) 
      REFERENCES BOOKS(BOOK_ID)
);

-- DROP SEQUENCE SEQ_AUTHOR_ID;

-- CREATE SEQUENCE SEQ_AUTHOR_ID
-- INCREMENT 1
-- START 1
-- OWNED BY AUTHORS.AUTHOR_ID;

SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;
SELECT * FROM BOOK_SALES;

INSERT INTO AUTHORS(NAME, EMAIL) VALUES ('Michal Books', 'michal.books@gmail.com');
INSERT INTO AUTHORS(NAME, EMAIL) VALUES ('Rachel Thomson', 'rachel.thomson@gmail.com');

INSERT INTO BOOKS(NAME, DESCRIPTION, DATE_CREATED, LAST_DATE_UPDATED, AUTHOR_ID)
	VALUES(
	'Sunny Evening',
	'Michal Books first book about a nice evenning he had', 
	CURRENT_TIMESTAMP, 
	NULL, 
	1);

UPDATE BOOKS SET description = 'Michal Books''s first book about a nice evenning he had',
	LAST_DATE_UPDATED = CURRENT_TIMESTAMP
	where name = 'Sunny Evening';


UPDATE BOOKS SET description = 'Michal Books''s second book about a not so nice afternoon he had',
	LAST_DATE_UPDATED = CURRENT_TIMESTAMP
	where name = 'Cloudy Afternoon';

INSERT INTO BOOKS(NAME, DESCRIPTION, DATE_CREATED, LAST_DATE_UPDATED, AUTHOR_ID)
	VALUES(
	'Sunny Evening',
	'Michal Books''s first book about a nice evenning he had', 
	CURRENT_TIMESTAMP, 
	NULL, 
	1);

INSERT INTO BOOKS(NAME, DESCRIPTION, DATE_CREATED, LAST_DATE_UPDATED, AUTHOR_ID)
	VALUES(
	'Cloudy Afternoon',
	'Michal Books''s second book about a not so nice afternoon he had', 
	CURRENT_TIMESTAMP, 
	NULL, 
	1);

INSERT INTO BOOKS(NAME, DESCRIPTION, DATE_CREATED, LAST_DATE_UPDATED, AUTHOR_ID)
	VALUES(
	'Emperor of the sun',
	'Rachel Thomson''s history book about the roman emperor Caligula', 
	CURRENT_TIMESTAMP, 
	NULL, 
	2);

INSERT INTO BOOK_SALES(PRICE_SOLD, DATE_SOLD, BOOK_ID)
	VALUES(
	12,
	CURRENT_TIMESTAMP,  
	1);

INSERT INTO BOOK_SALES(PRICE_SOLD, DATE_SOLD, BOOK_ID)
	VALUES(
	11,
	CURRENT_TIMESTAMP,  
	1);


INSERT INTO BOOK_SALES(PRICE_SOLD, DATE_SOLD, BOOK_ID)
	VALUES(
	10,
	CURRENT_TIMESTAMP,  
	1);


INSERT INTO BOOK_SALES(PRICE_SOLD, DATE_SOLD, BOOK_ID)
	VALUES(
	6,
	CURRENT_TIMESTAMP,  
	2);

INSERT INTO BOOK_SALES(PRICE_SOLD, DATE_SOLD, BOOK_ID)
	VALUES(
	7,
	CURRENT_TIMESTAMP,  
	2);


INSERT INTO BOOK_SALES(PRICE_SOLD, DATE_SOLD, BOOK_ID)
	VALUES(
	5,
	CURRENT_TIMESTAMP,  
	2);


